---
- name: Linux hosts restart
  hosts: all
  gather_facts: no
  remote_user: ec2-user
  serial: 1
  max_fail_percentage: 10
  become: true
  tasks: 
    - name: Check if a reboot is needed on AWS EC2 based servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no
    
    - Executing uptime before restart
      command: uptime
     
    - name: Reboot the box if kernel updated/installed on EC2 
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
   
    - name: Executing uptime to ensure the restart
      command: uptime
      
   #ansible-playbook <script> 
